# Generated by Django 5.1 on 2024-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0002_practicemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicemodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
